# Generated by Django 3.2.16 on 2022-12-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('music_id', models.AutoField(primary_key=True, serialize=False, verbose_name='music_id')),
                ('file', models.FileField(default='default.mp3', upload_to='musics/')),
                ('name', models.CharField(max_length=50)),
                ('upload_dt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('upload_dt',),
            },
        ),
    ]
