# Generated by Django 3.2.16 on 2022-12-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dance',
            fields=[
                ('dance_id', models.AutoField(primary_key=True, serialize=False, verbose_name='dance_id')),
                ('file', models.FileField(default='noname.mp3', upload_to='dance/')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DT')),
            ],
        ),
    ]
