# Generated by Django 3.2.16 on 2022-12-28 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dance', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dance',
            name='music',
            field=models.ForeignKey(db_column='music_id', on_delete=django.db.models.deletion.CASCADE, related_name='dance_music', to='music.music'),
        ),
        migrations.AddField(
            model_name='dance',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='dance_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
