# Generated by Django 3.2.16 on 2022-12-28 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='record_id')),
                ('file', models.FileField(default='noname.mp4', upload_to='record/')),
                ('create_dt', models.DateTimeField(auto_now_add=True, verbose_name='CREATE DT')),
                ('dance_id', models.ForeignKey(db_column='dance_id', on_delete=django.db.models.deletion.PROTECT, related_name='dance', to='dance.dance')),
                ('user', models.ForeignKey(db_column='r_user', on_delete=django.db.models.deletion.PROTECT, related_name='r_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
